name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20.19.0'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build docs index
        run: npm run build-docs-index
      - name: Publish Docs to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: 'WorkAI Bot'
          user_email: 'bot@workai.example'
